from snakemake.io import expand, directory, touch, multiext


rule all:
    input:
        expand("results/final/{sample}.done", sample=config["samples"]),


rule build_database:
    """
    Build a database from the input genome assembly
    """
    input:
        genome="data/{sample}.fasta.gz",
    output:
        multiext("results/rmod_database/{sample}/{sample}_rmod", ".nhr", ".nin", ".njs", ".nnd", ".nni", ".nog", ".nsq"),
        translation="results/rmod_database/{sample}/{sample}_rmod.translation",
    log:
        "logs/{sample}_build_database.log",
    conda:
        "envs/repeatmodeler.yaml"
    params:
        basename=lambda wildcards: f"results/rmod_database/{wildcards.sample}/{wildcards.sample}_rmod",
    shell:
        """BuildDatabase -name {params.basename} {input.genome} &> {log}"""


rule repeatmodeler:
    """
    Run RepeatModeler2 using the database files from the previous rule
    """
    input:
        nhr="results/rmod_database/{sample}/{sample}_rmod.nhr",
    output:
        families="results/rmod_families/{sample}/{sample}_rmod-families.fa",
    log:
        "logs/{sample}_run_repeatmodeler2.log",
    threads: 8
    conda:
        "envs/repeatmodeler.yaml"
    params:
        db_basename=lambda wildcards, input: input.nhr.replace(".nhr", ""),
    script:
        "scripts/run_repeatmodeler.py"


rule collect_te:
    input:
        families="results/rmod_families/{sample}/{sample}_rmod-families.fa",
    output:
        collection="results/collect_te/{sample}/{sample}_family.fa",
    log:
        "logs/{sample}_collect_te.log",
    params:
        te_name=config.get("te_name", ""),
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/collect_te.py"


rule repeatmasker:
    input:
        fasta="data/{sample}.fasta.gz",
        te_lib="results/collect_te/{sample}/{sample}_family.fa",
    output:
        masked_fasta="results/repeatmasker/{sample}/{sample}.fasta.masked",
        out_file="results/repeatmasker/{sample}/{sample}.fasta.out",
        cat_file="results/repeatmasker/{sample}/{sample}.fasta.cat.gz",
        gff="results/repeatmasker/{sample}/{sample}.fasta.out.gff",
    log:
        "logs/{sample}_repeatmasker.log",
    params:
        dir="results/repeatmasker/{sample}/",
        engine="wublast",
        extra=" -s -nocut",
    threads: 8
    conda:
        "envs/repeatmasker.yaml"
    shell:
        """
        # RepeatMasker outputs to the same directory as the input FASTA by default.
        # We use -dir to redirect it to our results folder.
        RepeatMasker \
            -pa {threads} \
            -lib {input.te_lib} \
            -dir {params.dir} \
            -gff \
            -engine {params.engine} \
            {params.extra} \
            {input.fasta} > {log} 2>&1
        """


rule final:
    input:
        gff="results/repeatmasker/{sample}/{sample}.fasta.out.gff",
    output:
        touch("results/final/{sample}.done"),
    shell:
        "echo 'Done'"
