default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500'] # Prevents accidentally committing large FASTQ/VCF files

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
      - id: reorder-python-imports
        args: ["--py3-plus"]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black # Auto-formats your code to PEP8 standards

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.11.2
    hooks:
      - id: snakefmt
        args: ["-l", "130"]
        files: ^workflow/(Snakefile|rules/.*\.smk)$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        files: ^workflow/scripts/.*\.py$
        args: ["--cov=workflow/scripts", "--cov-fail-under=80"]
