repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500'] # Prevents accidentally committing large FASTQ/VCF files

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black # Auto-formats your code to PEP8 standards

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        files: \.(py|R)$
        args: ["--cov=.", "--cov-fail-under=90"]
