[workspace]
name = "MGERT2"
description = "MGERT2 pipeline"
version = "0.0.0"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
dry-run = "snakemake -n --cores 1 --use-conda --configfile config/config.yaml"
full-run = "snakemake --cores 4 --use-conda --configfile config/config.yaml"
format-snakefile = "snakefmt -l 130 workflow/Snakefile"
lint = "snakemake --lint --configfile config/config.yaml"
format-scripts = "snakefmt -l 130 workflow/scripts/*.py"
unlock = "snakemake --unlock"
rulegraph = { cmd = "dot -c && snakemake --rulegraph --configfile config/config.yaml | dot -Tsvg > images/rulegraph.svg" }
dag = { cmd = "dot -c && snakemake --dag --configfile config/config.yaml | dot -Tsvg > images/dag.svg" }
tests = "pytest tests/"
pre-commit = "pre-commit run pytest-check --files workflow/scripts/*.py"
md-lint = "markdownlint-cli2 README.md --fix"

[dependencies]
snakemake = "9.13.5.*"
snakefmt = ">=0.11.2,<0.12"
pytest = ">=9.0.2,<10"
pycodestyle = ">=2.14.0,<3"
pytest-cov = ">=7.0.0,<8"
biopython = ">=1.86,<2"
python = ">=3.13.11,<3.14"
micromamba = ">=2.5.0,<3"
python-graphviz = ">=0.21,<0.22"
cairo = ">=1.18.4,<2"
pango = ">=1.56.4,<2"
conda = ">=25.11.1,<26"
pre-commit = ">=4.5.1,<5"
markdownlint-cli2 = ">=0.20.0,<0.21"
pandas = ">=3.0.0,<4"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.1,<3"
