name: Small integration test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run Snakemake integration test
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: tests/integration
          snakefile: workflow/Snakefile
          args: >-
            --use-conda
            --cores 2
            --configfile tests/integration/config/config.yaml
            --show-failed-logs
