on:
  push:
    branches:
      - main
      - dev

jobs:
  check_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
